## pytorch

In [6]:

import torch
X = torch.rand(3,3)
print(X)


tensor([[0.1262, 0.1865, 0.3316],
        [0.6599, 0.6927, 0.8326],
        [0.4515, 0.8671, 0.0990]])


In [7]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# creating tensor
#scalar

scalar= torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [148]:
#get tensor back as python int
scalar.item()

7

In [9]:
vector= torch.tensor([7, 7])
vector

tensor([7, 7])

In [150]:
vector.ndim

1

In [151]:
vector.shape

torch.Size([2])

In [152]:
# matrix

MATRIX= torch.tensor([[7,7],[9,9]])
print(MATRIX.shape)
MATRIX.ndim

torch.Size([2, 2])


2

In [153]:
# TENSOR
TENSOR= torch.tensor([[[1,2,3],[6,5,4],[9,8,7]]])
TENSOR.shape
# tensor and matrix are generally represented in uppercase.
# If you have: tensor = torch.randn(32, 3, 224, 224) It means: 32 = batch size (32 images): 3 = channels (e.g., RGB): 224 x 224 = height x width

torch.Size([1, 3, 3])

In [154]:
Random tensor

SyntaxError: invalid syntax (4284142924.py, line 1)

In [ ]:
# why ramdom tensor?
# random tensor are important because the way many neural network learn is that they start with tensor full of ramdom numbers and then adjust those ramdom number to better represent the data.
#start with ramdom number -> look at data -> update random numbers -> look at data ->update

random_tensor= torch.rand(10,10)
random_tensor


tensor([[0.9937, 0.5022, 0.4339, 0.9318, 0.2435, 0.6719, 0.0540, 0.9419, 0.8598,
         0.9033],
        [0.9770, 0.9738, 0.0026, 0.1747, 0.9306, 0.9824, 0.4155, 0.8703, 0.7518,
         0.2544],
        [0.6429, 0.9249, 0.5877, 0.7817, 0.8762, 0.0394, 0.6087, 0.8568, 0.7413,
         0.8126],
        [0.4927, 0.4159, 0.6225, 0.4084, 0.8664, 0.7455, 0.8386, 0.8706, 0.4058,
         0.5388],
        [0.5928, 0.1475, 0.4368, 0.0446, 0.1447, 0.8610, 0.6943, 0.6800, 0.1531,
         0.3395],
        [0.3026, 0.1485, 0.1518, 0.6898, 0.2973, 0.4007, 0.1279, 0.4816, 0.0755,
         0.4168],
        [0.6032, 0.9301, 0.7957, 0.4319, 0.5780, 0.3931, 0.9269, 0.6401, 0.6530,
         0.2649],
        [0.7942, 0.7102, 0.0207, 0.4483, 0.4623, 0.4288, 0.6135, 0.4635, 0.3587,
         0.8470],
        [0.0658, 0.3038, 0.5583, 0.8279, 0.8095, 0.9491, 0.1631, 0.1156, 0.6326,
         0.6004],
        [0.5713, 0.8394, 0.8871, 0.8006, 0.9741, 0.7104, 0.8749, 0.9689, 0.0986,
         0.8575]])

In [ ]:
print(random_tensor.ndim)
random_tensor2= torch.rand(3,2,2)
print(random_tensor2)
print(random_tensor2.ndim)

2
tensor([[[0.3077, 0.4839],
         [0.3913, 0.4452]],

        [[0.2631, 0.9352],
         [0.4007, 0.2030]],

        [[0.1640, 0.2615],
         [0.4463, 0.9973]]])
3


IMAGE TENSOR

In [ ]:
# VVV important VVV
# create a random tensor with similar shape to an image tensor

random_image_tensor = torch.rand(size=(224,224,3))  # 224x224 image with 3 color channels (RGB) where 224 is the height and width of the image and size is the shape of the image tensor
print(random_image_tensor.shape)
# create a random tensor with similar shape to a multi-channel image tensor
random_multi_channel_image_tensor = torch.rand(2, 3, 224, 224)  # 10 images, each with 3 channels and 224x224 pixels
print(random_multi_channel_image_tensor.shape)
print(random_multi_channel_image_tensor.ndim)
print(random_multi_channel_image_tensor)

Zeros, Ones and range and tensor like

In [ ]:
# random tensor with zeros and ones
random_zeros = torch.zeros(size=(3, 4))
print(random_zeros)
random_ones = torch.ones(size=(3, 4))
print(random_ones)
# creating a range of numbers
random_range = torch.arange(0, 20, 1)  # start, end, step
print(random_range)
# creating tensor like another tensor but with zeros
tensor_like = torch.zeros_like(random_range)  # creates a tensor of zeros with the same shape as random_tensor
print(tensor_like)
tensor_like2 = torch.ones_like(random_range)  # creates a tensor of ones with the same shape as random_tensor
print(tensor_like2)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


# Tensor datatypes
 **NOtes:** Tensor datatype is one of the 3 error we'll run into with PyTorch and deep learning
  1. Tensor not right datatype
  2. Tensor not right shape
  3. tensor is no right device
  


In [ ]:
# float 32 tensor
float_tensor = torch.tensor([3.0, 6.0, 9.0], 
                            dtype=torch.float16, # we can use nonetype for float 32 tensor and used  for precision
                            device=None,           # device=None,  # use 'cuda' for GPU or 'cpu' for CPU
                            requires_grad=False)  # requires_grad=True if you want to track gradients for backpropagation
print(float_tensor.dtype)

# changing the datatype of a tensor
float_tensor2= float_tensor.type(torch.int32)  # change to float32
print(float_tensor2.dtype)

ff= float_tensor2 * float_tensor
print(ff)


torch.float16
torch.int32
tensor([ 9., 36., 81.], dtype=torch.float16)


### Getting information from tensor

1. Tensor not right datatype - tensor.dtype eg: ff.dtype
2. Tensor not right shape - tensor.shape
3. tensor is no right device - tensor.device


## Manupulating tensors or tensor operations

* Addition
* Subtraction
* Multiplication (element-wise)
* Division (element-wise)
* Matrix multiplication (@)

In [ ]:
sample= torch.tensor([1,2,3,4,5])
print(sample + 10)
print(sample * 10)
print(sample - 10)
print(sample / 10)
print(sample ** 2)  # square each element
print(torch.pow(sample, 2))  # another way to square each element and can do this this with addition, subtraction, multiplication, division
print(sample % 2)  # modulus operation

# Matrix multiplication or dot product
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2= torch.tensor([[5,6],[7,8]])
print(tensor1 @ tensor2)  # matrix multiplication using @ operator
print(tensor2 @ tensor1)
# or using torch.matmul
print(torch.matmul(tensor1, tensor2))  # matrix multiplication using torch.matmul
# or using torch.mm
print(torch.mm(tensor1, tensor2))  # matrix multiplication using torch.mm
# element-wise multiplication
print(tensor1 * tensor2)  # element-wise multiplication

tensor3= torch.tensor([[1, 2, 3],[5,6,7]]) 
print(tensor3.shape)
print(tensor3.ndim)
print(torch.matmul(tensor3, tensor3.T))  # matrix multiplication with transpose
print( tensor3 ** 2)


tensor([11, 12, 13, 14, 15])
tensor([10, 20, 30, 40, 50])
tensor([-9, -8, -7, -6, -5])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000])
tensor([ 1,  4,  9, 16, 25])
tensor([ 1,  4,  9, 16, 25])
tensor([1, 0, 1, 0, 1])
tensor([[19, 22],
        [43, 50]])
tensor([[23, 34],
        [31, 46]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])
tensor([[ 5, 12],
        [21, 32]])
torch.Size([2, 3])
2
tensor([[ 14,  38],
        [ 38, 110]])
tensor([[ 1,  4,  9],
        [25, 36, 49]])


# find the min, max, mean, sum, etc ( tensor aggregation)


In [ ]:
tensor3= torch.randint(2, 100, (5,6)) 
tensor3 = tensor3.type(torch.float32)  # convert to float32 for precision
print("\n tensor3:")
print(tensor3)
print(tensor3.shape)

print("\n minimum value in the tensor:")
print(tensor3.min())  # minimum value in the tensor
print("\n maximum value in the tensor:")
print(tensor3.max())  # maximum value in the tensor
print("\n sum of all elements in the tensor:")
print(tensor3.sum())  # sum of all elements in the tensor
print("\n mean of all elements in the tensor:")
print(tensor3.mean())  # mean of all elements in the tensor
print("\n standard deviation of all elements in the tensor:")
print(tensor3.std())  # standard deviation of all elements in the tensor
print("\n variance of all elements in the tensor:")
print(tensor3.var())  # variance of all elements in the tensor
print("\n index of the minimum value in the tensor:")
print(tensor3.argmin())  # index of the minimum value in the tensor
print("\n index of the maximum value in the tensor:")
print(tensor3.argmax())  # index of the maximum value in the tensor
print("\n the minimum value in the tensor along dimension 0:")
print(tensor3.min(dim=0))  # index of the minimum value in the tensor along dimension 0
print("\n the maximum value in the tensor along dimension 1:")
print(tensor3.max(dim=1))  # index of the maximum value in the tensor along dimension 1
print("\n the  median value in the tensor")
print(tensor3.median())  # median value in the tensor 


 tensor3:
tensor([[33.,  7., 26., 21., 58., 40.],
        [49., 61., 44., 58., 37., 62.],
        [87., 57., 56., 99., 57., 21.],
        [93., 58., 64., 73., 66., 60.],
        [33., 84., 55., 42., 82., 26.]])
torch.Size([5, 6])

 minimum value in the tensor:
tensor(7.)

 maximum value in the tensor:
tensor(99.)

 sum of all elements in the tensor:
tensor(1609.)

 mean of all elements in the tensor:
tensor(53.6333)

 standard deviation of all elements in the tensor:
tensor(22.5381)

 variance of all elements in the tensor:
tensor(507.9644)

 index of the minimum value in the tensor:
tensor(1)

 index of the maximum value in the tensor:
tensor(15)

 the minimum value in the tensor along dimension 0:
torch.return_types.min(
values=tensor([33.,  7., 26., 21., 37., 21.]),
indices=tensor([0, 0, 0, 0, 1, 2]))

 the maximum value in the tensor along dimension 1:
torch.return_types.max(
values=tensor([58., 62., 99., 93., 84.]),
indices=tensor([4, 5, 3, 0, 1]))

 the  median value in the tens

# Reshaping, stacking,  squeezing and unsqueezing

* Reshaping= reshapes an input tensor to a defined shape
* View -  return a view of an input tensor of certain shape but keep the same memory as the orginal tensor
* Stacking - combine multiple tensors on the top of each other (vstack) or side by side (hstack)
* Squeezing -  remove all "1" dimension from a tensor
* Unsqueezing - add a"1" dimension to a targeted tensor
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way.

In [ ]:
tensor5= torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(tensor5)
print(tensor5.shape)

print(" \n reshaping the tensor to a different shape:")
reshaped_tensor = tensor5.reshape(3, 4)  # reshape to 3 rows and 4 columns
print(reshaped_tensor)
reshaped_tensor[0,0] = 15 # change the first column to 15
print(f" \n the original tensor: {tensor5}")
print(f" \n reshaped_tensor: {reshaped_tensor}")
print("\n \n reshaping the tensor to a different shape using reshape:")
reshaped_tensor2 = tensor5.reshape(2, 6)  # reshape to 2 rows and 6 columns
print(reshaped_tensor2)
print(reshaped_tensor2.shape)

print(" \n reshaping the tensor to a different shape using view:")
viewed_tensor = tensor5.view(6, 2)  # view to 3 rows and 4 columns
viewed_tensor[0, 0] = 20  # change the first column to 20
print(f"\n viewed_tensor after changing the first column to 20: {viewed_tensor}")
print(viewed_tensor.shape)
print(" \n original tensor after changing the first column of viewed_tensor: ", tensor5)
print(" \n reshaping the tensor to a different shape using flatten: to a 1D tensor")
flattened_tensor = tensor5.flatten()  # flatten the tensor to a 1D tensor
print(flattened_tensor)


tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
torch.Size([4, 3])
 
 reshaping the tensor to a different shape:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
 
 the original tensor: tensor([[15,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
 
 reshaped_tensor: tensor([[15,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

 
 reshaping the tensor to a different shape using reshape:
tensor([[15,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
torch.Size([2, 6])
 
 reshaping the tensor to a different shape using view:

 viewed_tensor after changing the first column to 20: tensor([[20,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])
torch.Size([6, 2])
 
 original tensor after changing the first column of viewed_tensor:  tensor([[20,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
 
 resh

In [ ]:
# stacking tensors
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])
# stacking along dimension 0 (rows)
stacked_tensor_0 = torch.stack([tensor_a, tensor_b], dim=0)  # stack along rows
print("\n Stacked tensor along dimension 0:")
print(stacked_tensor_0)
# stacking along dimension 1 (columns)
stacked_tensor_1 = torch.stack([tensor_a, tensor_b], dim=1)  # stack along columns
print("\n Stacked tensor along dimension 1:")
print(stacked_tensor_1)
# stacking along dimension 2 (depth)
stacked_tensor_2 = torch.stack([tensor_a, tensor_b], dim=2)  # stack along depth
print("\n Stacked tensor along dimension 2:")
print(stacked_tensor_2)
# concatenating tensors
tensor_c = torch.tensor([[9, 10], [11, 12]])
# concatenating along dimension 0 (rows)
concatenated_tensor_0 = torch.cat([tensor_a, tensor_c], dim=0)  # concatenate along rows
print("\n Concatenated tensor along dimension 0:")
print(concatenated_tensor_0)
# concatenating along dimension 1 (columns)
concatenated_tensor_1 = torch.cat([tensor_a, tensor_c], dim=1)  # concatenate along columns
print("\n Concatenated tensor along dimension 1:")
print(concatenated_tensor_1)



 Stacked tensor along dimension 0:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

 Stacked tensor along dimension 1:
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])

 Stacked tensor along dimension 2:
tensor([[[1, 5],
         [2, 6]],

        [[3, 7],
         [4, 8]]])

 Concatenated tensor along dimension 0:
tensor([[ 1,  2],
        [ 3,  4],
        [ 9, 10],
        [11, 12]])

 Concatenated tensor along dimension 1:
tensor([[ 1,  2,  9, 10],
        [ 3,  4, 11, 12]])


You started with this tensor:

python
Copy
Edit
tensor5 = torch.tensor([[1, 2, 3, 4 , 5, 6, 7, 8, 9, 10, 11, 12]])
This is a 2D tensor with shape:

python
Copy
Edit
torch.Size([1, 12])
Meaning:

1 row

12 columns

✅ 1. tensor5.unsqueeze(0)
python
Copy
Edit
tensor_new = tensor5.unsqueeze(0)
print(tensor_new.ndim)  # 3
print(tensor_new.shape) # torch.Size([1, 1, 12])
📌 What happened?

You added a new dimension at index 0.

The shape went from [1, 12] → [1, 1, 12].

Now it's a 3D tensor:

1 batch

1 row

12 columns

✅ 2. tensor5.unsqueeze(2)
python
Copy
Edit
tensor_new = tensor5.unsqueeze(2)
print(tensor_new.ndim)  # 3
print(tensor_new.shape) # torch.Size([1, 12, 1])
📌 What happened?

You added a new dimension at index 2 (after the 12).

The shape changed: [1, 12] → [1, 12, 1]

So now it's:

1 batch

12 rows

1 column per row

Each number is now in its own little column vector.

Example:

python
Copy
Edit
tensor([[[ 1],
         [ 2],
         [ 3],
         ...
         [12]]])
✅ 3. tensor5.unsqueeze(1)
python
Copy
Edit
tensor_new = tensor5.unsqueeze(1)
print(tensor_new.ndim)  # 3
print(tensor_new.shape) # torch.Size([1, 1, 12])
📌 What happened?

You added a new dimension at index 1 (between batch and columns).

Shape went from [1, 12] → [1, 1, 12], same as unsqueeze(0) in this specific case because there's only one row.



In [ ]:
tensor5= torch.tensor([[1, 2, 3, 4 , 5, 6, 7, 8, 9, 10, 11, 12]])
tensor_new= tensor5.unsqueeze(0) # add a new dimension at index 0
print(tensor_new.ndim)  # check the number of dimensions
print(tensor_new)
tensor_new= tensor5.unsqueeze(2) # add a new dimension at index 2
print(tensor_new.ndim)  # check the number of dimensions
print(tensor_new)
tensor_new= tensor5.unsqueeze(1)  # add a new dimension at index 1
print(tensor_new.ndim)  # check the number of dimensions
tensor_old= tensor5.squeeze() # squeeeze the tensor only if it is squeezable
print(tensor_new)
print(tensor_old)

3
tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]])
3
tensor([[[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11],
         [12]]])
3
tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


In [ ]:
# Permutations
tensor6 = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print("\n Original tensor:")
print(tensor6)
print("Shape of original tensor:", tensor6.shape)
# Permuting dimensions
permuted_tensor = tensor6.permute(2, 1, 0)  # swap rows and columns
print("\n Permuted tensor (swapped rows and columns):")
print(permuted_tensor)
print("Shape of permuted tensor:", permuted_tensor.shape)

# original tensor consist of a single batch of 3x3 matrix but after permutation it becomes a 3 batch of 3x1 matrix

print( tensor6 @ permuted_tensor)


 Original tensor:
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape of original tensor: torch.Size([1, 3, 3])

 Permuted tensor (swapped rows and columns):
tensor([[[1],
         [4],
         [7]],

        [[2],
         [5],
         [8]],

        [[3],
         [6],
         [9]]])
Shape of permuted tensor: torch.Size([3, 3, 1])
tensor([[[ 30],
         [ 66],
         [102]],

        [[ 36],
         [ 81],
         [126]],

        [[ 42],
         [ 96],
         [150]]])


# Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
print("\n Original tensor x:")
print(x)
print("Shape of original tensor x:", x.shape)



 Original tensor x:
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape of original tensor x: torch.Size([1, 3, 3])


In [ ]:
x[:,:,1]= 100  # change the value of the second row to 100
print("\n Modified tensor x after changing the second row to 100:")
print(x)


 Modified tensor x after changing the second row to 100:
tensor([[[  1, 100,   3],
         [  4, 100,   6],
         [  7, 100,   9]]])


In [ ]:
x[:, 1, 2] = 200  # change the value of the second row and second column to 200
print("\n Modified tensor x after changing the second row and second column to 200:")
print(x)



 Modified tensor x after changing the second row and second column to 200:
tensor([[[  1,   2,   3],
         [100, 100, 200],
         [  7,   8,   9]]])


# PyTorch and Numpy

Numpy is a popular scientific python numerical computing library

and because of this, Pytorch has functionality to interact withit

* Data in NUmpy, want in Pytorch tensor -> 'torch.from_numpy(ndarray)'
* Pytorch tensor -> NUmpy -> torch.Tensor.numpy()



In [165]:
# Numpy array to tensor

import numpy as np
import torch

array= np.array(range(1,11), dtype=np.float32)  # create a numpy array with float32 data type
print(array)

tensor = torch.from_numpy(array)

print(array, tensor, tensor.dtype)

print(torch.arange(1,10).type(torch.float32))  # create a tensor with float32 data type


# Tensor to Numpy array
tensorr = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)  # create a tensor with float32 data type
numpy_array = tensorr.numpy()  # convert tensor to numpy array
print(f"\n \nNumpy array before change: {numpy_array, numpy_array.dtype}")

# changing the data in numpy array will not change the data in the tensor
tensorr[:] = 100  # change the first element of the tensor
print("Tensor after changing the first element:", tensorr)
print("Numpy array after changing the first element of the tensor:", numpy_array)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) torch.float32
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

 
Numpy array before change: (array([1., 2., 3., 4., 5.], dtype=float32), dtype('float32'))
Tensor after changing the first element: tensor([100., 100., 100., 100., 100.])
Numpy array after changing the first element of the tensor: [100. 100. 100. 100. 100.]


# Reproducibility
Trying to take random out of random

In short how a neural network learns:
" Start with random number -> tensor operation -> update random numbers to try and make them better representation of the data -> again -> again -> again........"

To reduce the randomness in neural network and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [168]:
random1= torch.rand(3,4)
random2= torch.rand(3,4)

print("\n Random tensor 1:")
print(random1)
print("\n Random tensor 2:")
print(random2)
print("\n", random1 == random2)  # check if the two tensors are equal


 Random tensor 1:
tensor([[0.0360, 0.4702, 0.0836, 0.4923],
        [0.0704, 0.6059, 0.6124, 0.5387],
        [0.5091, 0.5222, 0.8164, 0.7432]])

 Random tensor 2:
tensor([[0.9152, 0.6875, 0.5310, 0.1687],
        [0.1298, 0.7734, 0.8088, 0.8516],
        [0.5172, 0.3096, 0.8823, 0.6121]])

 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [170]:
# lets' make some random but reproducible tensors
torch.manual_seed(42)  # set the random seed for reproducibility
random_tensor1 = torch.rand(3, 4)
random_tensor2 = torch.rand(3, 4)
print("\n Random tensor 1 with seed 42:")
print(random_tensor1)
print("\n Random tensor 2 with seed 42:")
print(random_tensor2)
# setting the random seed again will give the same random tensor
torch.manual_seed(42)  # set the random seed for reproducibility
random_tensor3 = torch.rand(3, 4)
random_tensor4 = torch.rand(3, 4)
print("\n Random tensor 3 with seed 42:")
print(random_tensor3)
print("\n Random tensor 4 with seed 42:")
print(random_tensor4)
# setting the random seed to a different value will give a different random tensor
torch.manual_seed(43)  # set the random seed to a different value
random_tensor5 = torch.rand(3, 4)
print("\n Random tensor 4 with seed 43:")
print(random_tensor5)


 Random tensor 1 with seed 42:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

 Random tensor 2 with seed 42:
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

 Random tensor 3 with seed 42:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

 Random tensor 4 with seed 42:
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

 Random tensor 4 with seed 43:
tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])


# GPU
runing tensor and pytorch objects on the GPUs (making fater computation)

1. Getting a GPU
2. Easiest way to get a GPU is to use Google Colab, which provides free access to GPUs.
2. Use your own GPU - takes a liitle bit of setup and requires the investment of purchasing a GPU.
3. Use a cloud provider - such as AWS, Azure, or GCP, which provide access to GPUs for a fee.
4. Use a local machine with a GPU - if you have a local machine with a GPU, you can use it for training your model

In [13]:
!nvidia-smi

Sat Jun 21 08:47:50 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.80                 Driver Version: 576.80         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce 940M          WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A    0C    P0            N/A  /  200W |       0MiB /   2048MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [23]:
#python.version
import sys
print(sys.version)  # print the python version
# torch.version
import torch
print(torch.__version__)  # print the torch version
# torch.cuda.is_available()
print(torch.cuda.is_available())  # check if CUDA is available
# torch.cuda.device_count()
print(torch.cuda.device_count())  # print the number of CUDA devices available

3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]
2.7.1+cpu
False
0


In [20]:
print(torch.__version__)
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)


2.7.1+cpu
Using device: cpu


In [8]:
tensor= torch.tensor([1, 2, 3, 4, 5], device= device)
print("Tensor on device:", tensor)
# Move tensor to GPU if available
if torch.cuda.is_available():
    tensor_gpu = tensor.to(device)
    print("Tensor moved to GPU:", tensor_gpu)
else:
    print("GPU not available, tensor remains on CPU:", tensor)
# Check if CUDA is available
if torch.cuda.is_available():
    print("CUDA is available")
else:
    print("CUDA is not available, using CPU instead")
# Check the number of available GPUs
num_gpus = torch.cuda.device_count()
print("Number of available GPUs:", num_gpus)
# Get the name of the current GPU
gpu_name = torch.cuda.get_device_name(0) if num_gpus > 0 else "No GPU available"
print("Current GPU name:", gpu_name)


Tensor on device: tensor([1, 2, 3, 4, 5])
GPU not available, tensor remains on CPU: tensor([1, 2, 3, 4, 5])
CUDA is not available, using CPU instead
Number of available GPUs: 0
Current GPU name: No GPU available
